settings:
  verbose: true
  remove_existing_files: false

generators:
- name: assignment template
  filename: assignment.tex
  parseargs: [$arg1, $arg2, $arg3]
- name: c source file
  filename: main.c
  parseargs: [$arg1, $arg2, $arg3]