settings:
  verbose: true
  remove_existing_files: false

generators:
- name: assignment template
  identifier: latexassingment
  filename: assignment.tex
- name: c source file
  identifier: cfile
  filename: main.c